In [2]:
import pandas as pd

In [5]:
data = pd.read_csv("Store_Data/ConsolidateOutput.csv")

In [16]:
data = data.drop(["Unnamed: 0.1", "Unnamed: 0"], axis = 1)

In [36]:
dataAvocado = data[ data["produce"].str.contains("Large Hass Avocado") ]

In [24]:
data.head()

                location                             produce    prices
0  Bedford New Hampshire  Organic Large Hass Avocado, 1 each     $1.99
1  Bedford New Hampshire          Large Hass Avocado, 1 each     $1.99
2  Bedford New Hampshire            Organic Honeycrisp Apple  $3.99/lb
3  Bedford New Hampshire        Whole Trade® Organic Bananas    69¢/lb
4  Bedford New Hampshire                    Organic Broccoli  $2.49/lb

In [37]:
dataAvocado

                  location                             produce prices
0    Bedford New Hampshire  Organic Large Hass Avocado, 1 each  $1.99
1    Bedford New Hampshire          Large Hass Avocado, 1 each  $1.99
40                 Beverly  Organic Large Hass Avocado, 1 each  $1.99
41                 Beverly          Large Hass Avocado, 1 each  $1.99
60               West Cary          Large Hass Avocado, 1 each  $1.99
100               Westford  Organic Large Hass Avocado, 1 each  $1.99
101               Westford          Large Hass Avocado, 1 each  $1.99
120          Union Station  Organic Large Hass Avocado, 1 each  $2.49
121          Union Station          Large Hass Avocado, 1 each  $1.99
140             Shrewsbury          Large Hass Avocado, 1 each  $1.99
180               Cityline          Large Hass Avocado, 1 each  $1.99
200       Madison Broadway  Organic Large Hass Avocado, 1 each  $2.49
201       Madison Broadway          Large Hass Avocado, 1 each  $1.99
220                 Irvine  Organic Large Hass Avocado, 1 each  $1.99
221                 Irvine          Large Hass Avocado, 1 each  $1.99
240                El Paso  Organic Large Hass Avocado, 1 each  $2.49
241                El Paso          Large Hass Avocado, 1 each  $1.99
261              Westchase  Organic Large Hass Avocado, 1 each  $1.99
262              Westchase          Large Hass Avocado, 1 each  $1.99
281            Las Colinas  Organic Large Hass Avocado, 1 each  $1.99
282            Las Colinas          Large Hass Avocado, 1 each  $1.99
301               Woodbury  Organic Large Hass Avocado, 1 each  $2.49
302               Woodbury          Large Hass Avocado, 1 each  $1.99